# Generated by Django 2.1.7 on 2019-03-24 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carnisseria', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='precuinats',
            name='date',
        ),
    ]
